### ISSUE TITLE
Problem in Gini formula [unless decided intentionally]

### ISSUE THREAD

**Issue by bedantaguru** [BoC-PaymentsResearch/CPMI_stats#2]
I was going through the implementation of the Gini coefficient. Looks like there is a (**probably**) mathematical error while adopting the weighted Gini coefficient.

Let me explain the problem in details : 
As per information available to me, the methodology adopted here is taken from  

> Bank of England: Working Paper No. 513: Variations in liquidity provision in real-time payment systems
> by **Edward Denbee, Rodney J Garratt and Peter Zimmerman**
> October 2014, revised January 2015 [(this paper)](https://www.bankofengland.co.uk/-/media/boe/files/working-paper/2014/variations-in-liquidity-provision-in-real-time-payment-systems)

_Please let me know if I'm wrong_
As per equation 6 of the paper, Gini coefficient  formula looks like 
<img src="https://latex.codecogs.com/gif.latex?G^s&space;=&space;\frac{1}{2M^2\mu}\left&space;(&space;\sum_{j=1}^{n}\sum_{k=1}^{n}m_jm_k\left&space;|&space;\mathit{l}_j^s-\mathit{l}_k^s&space;\right&space;|)&space;\right&space;)&space;\&space;with&space;\&space;\mathit{l}_j^s&space;=&space;\frac{L_j^s}{P_j^s}" title="G^s = \frac{1}{2M^2\mu}\left ( \sum_{j=1}^{n}\sum_{k=1}^{n}m_jm_k\left | \mathit{l}_j^s-\mathit{l}_k^s \right |) \right ) \ with \ \mathit{l}_j^s = \frac{L_j^s}{P_j^s}" />
where μ is the average liquidity cost of all payments and M is the total number of payments made by all banks.

But if you notice carefully actual expression should be like 
<img src="https://latex.codecogs.com/gif.latex?G^s&space;=&space;\frac{1}{2{M^s}^{2}\mu^s}\left&space;(&space;\sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left&space;|&space;\mathit{l}_j^s-\mathit{l}_k^s&space;\right&space;|)&space;\right&space;)" title="G^s = \frac{1}{2{M^s}^{2}\mu^s}\left ( \sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left | \mathit{l}_j^s-\mathit{l}_k^s \right |) \right )" />

Note here, the expression for μ  and M was not mentioned as the formula in the main paper. 

As per the definition is given in [this paper](https://www.victoria.ac.nz/sacl/centres-and-chairs/cpf/publications/pdfs/2015-pubs/WP03_2015_Gini_Inequality.pdf) by John Creedy (equation 15) and formula used in [Wikipedia](https://en.wikipedia.org/wiki/Gini_coefficient#Calculation) (case of Discrete probability distribution) the formula of μ  and M can be obtained. 
Replacing these formula in above equation we have formula for Gini coefficient as 
<img src="https://latex.codecogs.com/gif.latex?G^s&space;=&space;\frac{1}{2{M^s}^{2}\mu^s}\left&space;(&space;\sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left&space;|&space;\mathit{l}_j^s-\mathit{l}_k^s&space;\right&space;|)&space;\right&space;)&space;\\&space;where&space;\&space;M^s&space;=&space;\sum_{j=1}^nm_j^s&space;\&space;and&space;\&space;\mu^s&space;=&space;\frac{\sum_{j=1}^nm_j^s\mathit{l}_j^s}{\sum_{j=1}^nm_j^s}" title="G^s = \frac{1}{2{M^s}^{2}\mu^s}\left ( \sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left | \mathit{l}_j^s-\mathit{l}_k^s \right |) \right ) \\ where \ M^s = \sum_{j=1}^nm_j^s \ and \ \mu^s = \frac{\sum_{j=1}^nm_j^s\mathit{l}_j^s}{\sum_{j=1}^nm_j^s}" />
Which is 
<img src="https://latex.codecogs.com/gif.latex?G^s&space;=&space;\frac{\left&space;(&space;\sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left&space;|&space;\mathit{l}_j^s-\mathit{l}_k^s&space;\right&space;|&space;\right&space;)}{2{\left&space;(\sum_{j=1}^nm_j^s&space;\right&space;)^2}{\frac{\left&space;(&space;\sum_{j=1}^nm_j^s\mathit{l}_j^s&space;\right&space;)}{\left&space;(\sum_{j=1}^nm_j^s&space;\right&space;)}}}" title="G^s = \frac{\left ( \sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left | \mathit{l}_j^s-\mathit{l}_k^s \right | \right )}{2{\left (\sum_{j=1}^nm_j^s \right )^2}{\frac{\left ( \sum_{j=1}^nm_j^s\mathit{l}_j^s \right )}{\left (\sum_{j=1}^nm_j^s \right )}}}" />

However look at the implementation of the same in https://github.com/BoC-PaymentsResearch/CPMI_stats/blob/4555ad50143ca6c7c04d0bcef240cb5d73efad43/R/gini_coefficient.R#L72
and 
https://github.com/BoC-PaymentsResearch/CPMI_stats/blob/4555ad50143ca6c7c04d0bcef240cb5d73efad43/R/gini_coefficient.R#L97
So the formula that got adopted in the code `CPMI_stats/R/gini_coefficient.R` is actually following 
<img src="https://latex.codecogs.com/gif.latex?G^s&space;=&space;\frac{\left&space;(&space;\sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left&space;|&space;\mathit{l}_j^s-\mathit{l}_k^s&space;\right&space;|&space;\right&space;)}{2{\left&space;(\sum_{j=1}^nm_j^s&space;\right&space;)^2}{\frac{\left&space;(&space;\sum_{j=1}^nP_j^s\mathit{l}_j^s&space;\right&space;)}{\left&space;(\sum_{j=1}^nP_j^s&space;\right&space;)}}}" title="G^s = \frac{\left ( \sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left | \mathit{l}_j^s-\mathit{l}_k^s \right | \right )}{2{\left (\sum_{j=1}^nm_j^s \right )^2}{\frac{\left ( \sum_{j=1}^nP_j^s\mathit{l}_j^s \right )}{\left (\sum_{j=1}^nP_j^s \right )}}}" />

If this is intentionally done for some analytical reasons then fine, otherwise I think one needs to finalize the correct formula for the Gini coefficient. (_This also helps in faster computation by derived formulas. See for example [weighted.gini](https://www.rdocumentation.org/packages/acid/versions/1.1/topics/weighted.gini)_)

Numerically the values are different and also theoretically only one type of weight should be used instead of two kinds of weights. Either volume or number of transaction has to be chosen as final weight. Which is a business decision (_and ideally should be taken before final implementation_). 

Kindly review and do the needful. Please let me know If I can be of any assistance.

**Comment by derekbrito** [comment]
You are right there was an error in the weighting. The code has been updated with the correct weighting. Thanks again for your help.

**Comment by bedantaguru** [comment]
Great. @derekbrito thanks for the clarification. We can create an Rmd including these formulae. 
So the correct formula then is 
<img src="https://latex.codecogs.com/gif.latex?G^s&space;=&space;\frac{\left&space;(&space;\sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left&space;|&space;\mathit{l}_j^s-\mathit{l}_k^s&space;\right&space;|&space;\right&space;)}{2{\left&space;(\sum_{j=1}^nm_j^s&space;\right&space;)^2}{\frac{\left&space;(&space;\sum_{j=1}^nm_j^s\mathit{l}_j^s&space;\right&space;)}{\left&space;(\sum_{j=1}^nm_j^s&space;\right&space;)}}}" title="G^s = \frac{\left ( \sum_{j=1}^{n}\sum_{k=1}^{n}m_j^sm_k^s\left | \mathit{l}_j^s-\mathit{l}_k^s \right | \right )}{2{\left (\sum_{j=1}^nm_j^s \right )^2}{\frac{\left ( \sum_{j=1}^nm_j^s\mathit{l}_j^s \right )}{\left (\sum_{j=1}^nm_j^s \right )}}}" />

If that is so then there can be even faster implementation. I'll share the code possibly by next week. 
Thanks for your support and prompt reply.
